### ISSUE TITLE
Move push demos to VAPID

### ISSUE THREAD

**Issue by delapuente** [mozilla/serviceworker-cookbook#290]

**Comment by slokhorst** [comment]
I'm trying to do this, but it requires storing the server's VAPID keys somewhere. (like how the GCM key is stored in `manifest.json` right now)

What is the best way to do this? Do we already depend on some kind of node.js storage library?

The alternative would be to invalidate the subscription (client-side) on every page load and create a new one. But that's not good practice to teach people and wasteful because we are creating and destroying subscriptions all the time.

**Comment by slokhorst** [comment]
There's a caveat here: If we switch to VAPID (remove GCM key), Chrome doesn't accept unencrypted push messages. Even when they have no data. This means that all push recipes will need the key handling/encryption code, even push-simple and push-get-payload. This makes them pretty much identical to push-payload, and they should probably be removed.

**Comment by slokhorst** [comment]
Fixed by #294
